kind: Service
apiVersion: v1
metadata:
  name: gateway-assets
  namespace: default
spec:
  selector:
    app: gateway-assets
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
